### ISSUE TITLE
alpha = 1000

### ISSUE THREAD

**Issue by liangsmfish** [xuzhengxiao/deep-photo-enhancer#1]
In train.py , you set alpha =1000 multiplied to I_loss and cycle_loss
Can you tell me that why do you set this config?
Thx !

**Comment by xuzhengxiao** [comment]
@liangsmfish alpha is hyper parameter which weights between the adversial loss and I/C loss,I guess author made experiments to demermine which value to use.If alpha is too small,the generated picture's content maybe different with source image.If it's value too big,the result may not have the hdr effect.

**Comment by liangsmfish** [comment]
I got it , thank you!
